# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170410_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
