# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chat_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='expired',
        ),
        migrations.AddField(
            model_name='chat',
            name='timeout',
            field=models.IntegerField(default=60),
        ),
    ]
