# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chat_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='expiration_time',
            field=models.BigIntegerField(default=1491857636.219661),
        ),
    ]
