# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170410_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='expiration_time',
            field=models.FloatField(default=1491857812.683481),
        ),
    ]
